name: test-shopper
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: "nodejs:20-alpine"
    container_name: nodejs
    env_file: .env
    environment:
      - NODE_ENV=$NODE_ENV
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    depends_on:
      postgres-db:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    networks:
      - app-network

  postgres-db:
    container_name: "postgres-db"
    image: "postgres:16-alpine"
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER} -h localhost",
        ]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  node_modules:
